name: My Story Workflow

on:
  
  push:
    branches: [ "main" ]
  pull_request:
    paths:
     - 'storybook/**'
  workflow_dispatch:
    inputs:
      story_title: 
        description: 'Write here title name'
        required: true
      author_name:
        description: 'Write here the name of the author'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run My Story
        run: |
          echo Once upon a time in a faraway land
          echo ${{ inputs.story_title }} was written by ${{ inputs.author_name }}
          echo This whimsical tale takes you on a journey through a magical forest where every flower could talk.
          echo Will you explore its secrets?
